// <auto-generated />
using System;
using Garden1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenProject.Migrations
{
    [DbContext(typeof(GardenContext))]
    [Migration("20230612005955_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garden1.Bed", b =>
                {
                    b.Property<int>("BedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BedId"));

                    b.Property<int>("GardenId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("BedId");

                    b.HasIndex("GardenId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("Garden1.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CropId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("Garden1.CropAssignment", b =>
                {
                    b.Property<int>("CropAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropAssignmentId"));

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CropAssignmentId");

                    b.HasIndex("BedId");

                    b.HasIndex("CropId");

                    b.HasIndex("ImageId");

                    b.ToTable("CropAssignments");
                });

            modelBuilder.Entity("Garden1.Garden", b =>
                {
                    b.Property<int>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GardenId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GardenId");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("Garden1.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Garden1.Bed", b =>
                {
                    b.HasOne("Garden1.Garden", "Garden")
                        .WithMany("Beds")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");
                });

            modelBuilder.Entity("Garden1.CropAssignment", b =>
                {
                    b.HasOne("Garden1.Bed", "Bed")
                        .WithMany("CropAssignments")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garden1.Crop", "Crop")
                        .WithMany("CropAssignments")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garden1.Image", "Image")
                        .WithMany("CropAssignments")
                        .HasForeignKey("ImageId");

                    b.Navigation("Bed");

                    b.Navigation("Crop");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Garden1.Bed", b =>
                {
                    b.Navigation("CropAssignments");
                });

            modelBuilder.Entity("Garden1.Crop", b =>
                {
                    b.Navigation("CropAssignments");
                });

            modelBuilder.Entity("Garden1.Garden", b =>
                {
                    b.Navigation("Beds");
                });

            modelBuilder.Entity("Garden1.Image", b =>
                {
                    b.Navigation("CropAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
